/**
 * Transactional email port — the domain only knows that emails get sent.
 * The Resend adapter (or a future provider) lives in shared/mail/adapters/.
 */
export interface SendMailInput {
  to: string;
  subject: string;
  /** HTML body. Plain-text fallback is generated by the adapter. */
  html: string;
}

export interface MailPort {
  send(input: SendMailInput): Promise<void>;
}

export const MAIL_PORT = Symbol("MAIL_PORT");
